/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vinculacion.educamoises.view.cuestionario;

/**
 *
 * @author fredd
 */
public class CuestionarioView2 extends javax.swing.JPanel {

    /**
     * Creates new form CuestionarioView2
     */
    public CuestionarioView2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        view2 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        containerCuestionario = new javax.swing.JPanel();

        setLayout(new java.awt.GridLayout(1, 0));

        view2.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(245, 201, 130));
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 50));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jRadioButton1.setBackground(new java.awt.Color(245, 201, 130));
        jRadioButton1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jRadioButton1.setText("Selección");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton1, new java.awt.GridBagConstraints());

        jRadioButton2.setBackground(new java.awt.Color(245, 201, 130));
        jRadioButton2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jRadioButton2.setText("Múltiple");
        jPanel2.add(jRadioButton2, new java.awt.GridBagConstraints());

        jRadioButton3.setBackground(new java.awt.Color(245, 201, 130));
        jRadioButton3.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jRadioButton3.setText("Abierta");
        jPanel2.add(jRadioButton3, new java.awt.GridBagConstraints());

        view2.add(jPanel2, java.awt.BorderLayout.NORTH);

        containerCuestionario.setBackground(new java.awt.Color(245, 201, 130));
        containerCuestionario.setPreferredSize(new java.awt.Dimension(400, 200));
        containerCuestionario.setLayout(new java.awt.BorderLayout());
        view2.add(containerCuestionario, java.awt.BorderLayout.CENTER);

        add(view2);
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel containerCuestionario;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JRadioButton jRadioButton1;
    public javax.swing.JRadioButton jRadioButton2;
    public javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JPanel view2;
    // End of variables declaration//GEN-END:variables
}
