package vinculacion.educamoises.view.estudios;

import java.awt.Button;
import javax.swing.JPanel;

/**
 *
 * @author Ana
 */
public class SocialViewCourse3 extends javax.swing.JPanel {

    /**
     * Creates new form MainView
     */
    public SocialViewCourse3() {
        initComponents();
        this.containerBtn.setLocation(150,250);
        setBackground(new JPanel().getBackground());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        containerPanels = new javax.swing.JPanel();
        center = new javax.swing.JPanel();
        containerBtn = new javax.swing.JPanel();
        btnE9 = new javax.swing.JButton();
        btnE11 = new javax.swing.JButton();
        btnE12 = new javax.swing.JButton();
        btnE13 = new javax.swing.JButton();
        btnE14 = new javax.swing.JButton();
        btnE15 = new javax.swing.JButton();
        btnE16 = new javax.swing.JButton();
        btnE5 = new javax.swing.JButton();
        btnE7 = new javax.swing.JButton();
        btnE2 = new javax.swing.JButton();
        btnE4 = new javax.swing.JButton();
        btnE3 = new javax.swing.JButton();
        btnE8 = new javax.swing.JButton();
        btnE1 = new javax.swing.JButton();
        btnE6 = new javax.swing.JButton();
        btnE10 = new javax.swing.JButton();
        volver = new javax.swing.JButton();
        text = new javax.swing.JLabel();
        nuevo = new javax.swing.JButton();
        text1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setMinimumSize(new java.awt.Dimension(800, 600));
        setLayout(new java.awt.GridLayout(1, 0));

        containerPanels.setMinimumSize(new java.awt.Dimension(800, 600));
        containerPanels.setLayout(new java.awt.BorderLayout());

        center.setBackground(new java.awt.Color(245, 201, 130));
        center.setMinimumSize(new java.awt.Dimension(600, 370));
        center.setPreferredSize(new java.awt.Dimension(400, 400));

        containerBtn.setBackground(new java.awt.Color(245, 201, 130));
        containerBtn.setAlignmentX(0.0F);
        containerBtn.setMinimumSize(new java.awt.Dimension(629, 370));

        btnE9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/p1.png"))); // NOI18N
        btnE9.setToolTipText("");
        btnE9.setBorder(null);
        btnE9.setBorderPainted(false);
        btnE9.setContentAreaFilled(false);
        btnE9.setFocusable(false);
        btnE9.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/p2.png"))); // NOI18N

        btnE11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/p1.png"))); // NOI18N
        btnE11.setToolTipText("");
        btnE11.setBorder(null);
        btnE11.setBorderPainted(false);
        btnE11.setContentAreaFilled(false);
        btnE11.setFocusable(false);
        btnE11.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/p2.png"))); // NOI18N

        btnE12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/p1.png"))); // NOI18N
        btnE12.setToolTipText("");
        btnE12.setBorder(null);
        btnE12.setBorderPainted(false);
        btnE12.setContentAreaFilled(false);
        btnE12.setFocusable(false);
        btnE12.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/p2.png"))); // NOI18N

        btnE13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/p1.png"))); // NOI18N
        btnE13.setToolTipText("");
        btnE13.setBorder(null);
        btnE13.setBorderPainted(false);
        btnE13.setContentAreaFilled(false);
        btnE13.setFocusable(false);
        btnE13.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/p2.png"))); // NOI18N

        btnE14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/p1.png"))); // NOI18N
        btnE14.setToolTipText("");
        btnE14.setBorder(null);
        btnE14.setBorderPainted(false);
        btnE14.setContentAreaFilled(false);
        btnE14.setFocusable(false);
        btnE14.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/p2.png"))); // NOI18N

        btnE15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/p1.png"))); // NOI18N
        btnE15.setToolTipText("");
        btnE15.setBorder(null);
        btnE15.setBorderPainted(false);
        btnE15.setContentAreaFilled(false);
        btnE15.setFocusable(false);
        btnE15.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/p2.png"))); // NOI18N

        btnE16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/p1.png"))); // NOI18N
        btnE16.setToolTipText("");
        btnE16.setBorder(null);
        btnE16.setBorderPainted(false);
        btnE16.setContentAreaFilled(false);
        btnE16.setFocusable(false);
        btnE16.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/p2.png"))); // NOI18N

        btnE5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/p1.png"))); // NOI18N
        btnE5.setToolTipText("");
        btnE5.setBorder(null);
        btnE5.setBorderPainted(false);
        btnE5.setContentAreaFilled(false);
        btnE5.setFocusable(false);
        btnE5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/p2.png"))); // NOI18N

        btnE7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/p1.png"))); // NOI18N
        btnE7.setToolTipText("");
        btnE7.setBorder(null);
        btnE7.setBorderPainted(false);
        btnE7.setContentAreaFilled(false);
        btnE7.setFocusable(false);
        btnE7.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/p2.png"))); // NOI18N

        btnE2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/p1.png"))); // NOI18N
        btnE2.setToolTipText("");
        btnE2.setBorder(null);
        btnE2.setBorderPainted(false);
        btnE2.setContentAreaFilled(false);
        btnE2.setFocusable(false);
        btnE2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/p2.png"))); // NOI18N

        btnE4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/p1.png"))); // NOI18N
        btnE4.setToolTipText("");
        btnE4.setBorder(null);
        btnE4.setBorderPainted(false);
        btnE4.setContentAreaFilled(false);
        btnE4.setFocusable(false);
        btnE4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/p2.png"))); // NOI18N

        btnE3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/p1.png"))); // NOI18N
        btnE3.setToolTipText("");
        btnE3.setBorder(null);
        btnE3.setBorderPainted(false);
        btnE3.setContentAreaFilled(false);
        btnE3.setFocusable(false);
        btnE3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/p2.png"))); // NOI18N

        btnE8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/p1.png"))); // NOI18N
        btnE8.setToolTipText("");
        btnE8.setBorder(null);
        btnE8.setBorderPainted(false);
        btnE8.setContentAreaFilled(false);
        btnE8.setFocusable(false);
        btnE8.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/p2.png"))); // NOI18N

        btnE1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/p1.png"))); // NOI18N
        btnE1.setToolTipText("");
        btnE1.setBorder(null);
        btnE1.setBorderPainted(false);
        btnE1.setContentAreaFilled(false);
        btnE1.setFocusable(false);
        btnE1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/p2.png"))); // NOI18N

        btnE6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/p1.png"))); // NOI18N
        btnE6.setToolTipText("");
        btnE6.setBorder(null);
        btnE6.setBorderPainted(false);
        btnE6.setContentAreaFilled(false);
        btnE6.setFocusable(false);
        btnE6.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/p2.png"))); // NOI18N

        btnE10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/p1.png"))); // NOI18N
        btnE10.setToolTipText("");
        btnE10.setBorder(null);
        btnE10.setBorderPainted(false);
        btnE10.setContentAreaFilled(false);
        btnE10.setFocusable(false);
        btnE10.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/p2.png"))); // NOI18N

        volver.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        volver.setText("Volver");
        volver.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        volver.setContentAreaFilled(false);
        volver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        volver.setFocusable(false);

        text.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        text.setForeground(new java.awt.Color(255, 102, 102));
        text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text.setText("Estudios Sociales");
        text.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        nuevo.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        nuevo.setText("Jugar de Nuevo");
        nuevo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        nuevo.setContentAreaFilled(false);
        nuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nuevo.setFocusable(false);
        nuevo.setRequestFocusEnabled(false);

        text1.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        text1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text1.setText("Lugares y Culturas de Ecuador");
        text1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout containerBtnLayout = new javax.swing.GroupLayout(containerBtn);
        containerBtn.setLayout(containerBtnLayout);
        containerBtnLayout.setHorizontalGroup(
            containerBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerBtnLayout.createSequentialGroup()
                .addGap(490, 490, 490)
                .addComponent(text)
                .addContainerGap(494, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerBtnLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(containerBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerBtnLayout.createSequentialGroup()
                        .addGroup(containerBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(containerBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnE1, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnE9, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnE6, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(btnE13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(containerBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(containerBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerBtnLayout.createSequentialGroup()
                                    .addComponent(btnE2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnE3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnE4))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerBtnLayout.createSequentialGroup()
                                    .addComponent(btnE5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnE7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnE8)))
                            .addGroup(containerBtnLayout.createSequentialGroup()
                                .addComponent(btnE14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnE15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnE16))
                            .addGroup(containerBtnLayout.createSequentialGroup()
                                .addComponent(btnE10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnE11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnE12)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(containerBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(volver, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nuevo))
                        .addGap(326, 326, 326))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerBtnLayout.createSequentialGroup()
                        .addComponent(text1, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(355, 355, 355))))
        );
        containerBtnLayout.setVerticalGroup(
            containerBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerBtnLayout.createSequentialGroup()
                .addComponent(text)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(text1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(containerBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerBtnLayout.createSequentialGroup()
                        .addComponent(nuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(volver))
                    .addGroup(containerBtnLayout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(btnE6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnE9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnE13))
                    .addGroup(containerBtnLayout.createSequentialGroup()
                        .addGroup(containerBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(containerBtnLayout.createSequentialGroup()
                                .addGroup(containerBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnE2)
                                    .addComponent(btnE3)
                                    .addComponent(btnE4)
                                    .addComponent(btnE1))
                                .addGap(5, 5, 5)
                                .addGroup(containerBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnE5)
                                    .addComponent(btnE7)))
                            .addGroup(containerBtnLayout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addComponent(btnE8)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(containerBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnE10)
                            .addComponent(btnE11)
                            .addComponent(btnE12))
                        .addGap(6, 6, 6)
                        .addGroup(containerBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnE15)
                            .addComponent(btnE14)
                            .addComponent(btnE16))))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        nuevo.getAccessibleContext().setAccessibleName("JugarDeNuevo");

        center.add(containerBtn);

        containerPanels.add(center, java.awt.BorderLayout.CENTER);

        add(containerPanels);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnE1;
    public javax.swing.JButton btnE10;
    public javax.swing.JButton btnE11;
    public javax.swing.JButton btnE12;
    public javax.swing.JButton btnE13;
    public javax.swing.JButton btnE14;
    public javax.swing.JButton btnE15;
    public javax.swing.JButton btnE16;
    public javax.swing.JButton btnE2;
    public javax.swing.JButton btnE3;
    public javax.swing.JButton btnE4;
    public javax.swing.JButton btnE5;
    public javax.swing.JButton btnE6;
    public javax.swing.JButton btnE7;
    public javax.swing.JButton btnE8;
    public javax.swing.JButton btnE9;
    private javax.swing.JPanel center;
    private javax.swing.JPanel containerBtn;
    private javax.swing.JPanel containerPanels;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JButton nuevo;
    private javax.swing.JLabel text;
    private javax.swing.JLabel text1;
    public javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
