/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vinculacion.educamoises.view.literatura.juego;

/**
 *
 * @author Edinson Ayui
 */
public class AhorcadoView extends javax.swing.JPanel {

    /**
     * Creates new form AhorcadoView
     */
    public AhorcadoView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnIniciar = new javax.swing.JButton();
        btnResolver = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txtPalabra = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        Erorres = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        button_A = new javax.swing.JButton();
        button_B = new javax.swing.JButton();
        button_C = new javax.swing.JButton();
        button_D = new javax.swing.JButton();
        button_E = new javax.swing.JButton();
        button_F = new javax.swing.JButton();
        button_G = new javax.swing.JButton();
        button_H = new javax.swing.JButton();
        button_I = new javax.swing.JButton();
        button_J = new javax.swing.JButton();
        button_K = new javax.swing.JButton();
        button_L = new javax.swing.JButton();
        button_M = new javax.swing.JButton();
        button_N = new javax.swing.JButton();
        button_Ñ = new javax.swing.JButton();
        button_O = new javax.swing.JButton();
        button_P = new javax.swing.JButton();
        button_Q = new javax.swing.JButton();
        button_R = new javax.swing.JButton();
        button_S = new javax.swing.JButton();
        button_T = new javax.swing.JButton();
        button_U = new javax.swing.JButton();
        button_V = new javax.swing.JButton();
        button_W = new javax.swing.JButton();
        button_X = new javax.swing.JButton();
        button_Y = new javax.swing.JButton();
        button_Z = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        Dibujo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(245, 201, 130));

        jPanel1.setBackground(new java.awt.Color(245, 201, 130));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Menu..."));

        btnIniciar.setText("Iniciar");

        btnResolver.setText("Resolver");

        btnSalir.setText("Salir");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnResolver, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnIniciar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnResolver, javax.swing.GroupLayout.PREFERRED_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(245, 201, 130));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Palabra Oculta"));

        txtPalabra.setEditable(false);
        txtPalabra.setBackground(new java.awt.Color(0, 0, 0));
        txtPalabra.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtPalabra.setForeground(new java.awt.Color(255, 255, 255));
        txtPalabra.setText("Palabra Oculta");
        txtPalabra.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtPalabra)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(txtPalabra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(245, 201, 130));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Errores"));

        Erorres.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ahorcado/fallo0.png"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Erorres)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(Erorres, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(245, 201, 130));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("   Teclado   "));
        jPanel4.setLayout(new java.awt.GridLayout(6, 5));

        button_A.setText("A");
        jPanel4.add(button_A);

        button_B.setText("B");
        jPanel4.add(button_B);

        button_C.setText("C");
        jPanel4.add(button_C);

        button_D.setText("D");
        jPanel4.add(button_D);

        button_E.setText("E");
        jPanel4.add(button_E);

        button_F.setText("F");
        jPanel4.add(button_F);

        button_G.setText("G");
        jPanel4.add(button_G);

        button_H.setText("H");
        jPanel4.add(button_H);

        button_I.setText("I");
        jPanel4.add(button_I);

        button_J.setText("J");
        jPanel4.add(button_J);

        button_K.setText("K");
        jPanel4.add(button_K);

        button_L.setText("L");
        jPanel4.add(button_L);

        button_M.setText("M");
        jPanel4.add(button_M);

        button_N.setText("N");
        jPanel4.add(button_N);

        button_Ñ.setText("Ñ");
        jPanel4.add(button_Ñ);

        button_O.setText("O");
        jPanel4.add(button_O);

        button_P.setText("P");
        jPanel4.add(button_P);

        button_Q.setText("Q");
        jPanel4.add(button_Q);

        button_R.setText("R");
        jPanel4.add(button_R);

        button_S.setText("S");
        jPanel4.add(button_S);

        button_T.setText("T");
        jPanel4.add(button_T);

        button_U.setText("U");
        jPanel4.add(button_U);

        button_V.setText("V");
        jPanel4.add(button_V);

        button_W.setText("W");
        jPanel4.add(button_W);

        button_X.setText("X");
        jPanel4.add(button_X);

        button_Y.setText("Y");
        jPanel4.add(button_Y);

        button_Z.setText("Z");
        jPanel4.add(button_Z);

        jPanel5.setBackground(new java.awt.Color(245, 201, 130));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Ahorcado"));

        Dibujo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ahorcado/Ahorcado0.png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Dibujo, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Dibujo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel Dibujo;
    public javax.swing.JLabel Erorres;
    public javax.swing.JButton btnIniciar;
    public javax.swing.JButton btnResolver;
    public javax.swing.JButton btnSalir;
    public javax.swing.JButton button_A;
    public javax.swing.JButton button_B;
    public javax.swing.JButton button_C;
    public javax.swing.JButton button_D;
    public javax.swing.JButton button_E;
    public javax.swing.JButton button_F;
    public javax.swing.JButton button_G;
    public javax.swing.JButton button_H;
    public javax.swing.JButton button_I;
    public javax.swing.JButton button_J;
    public javax.swing.JButton button_K;
    public javax.swing.JButton button_L;
    public javax.swing.JButton button_M;
    public javax.swing.JButton button_N;
    public javax.swing.JButton button_O;
    public javax.swing.JButton button_P;
    public javax.swing.JButton button_Q;
    public javax.swing.JButton button_R;
    public javax.swing.JButton button_S;
    public javax.swing.JButton button_T;
    public javax.swing.JButton button_U;
    public javax.swing.JButton button_V;
    public javax.swing.JButton button_W;
    public javax.swing.JButton button_X;
    public javax.swing.JButton button_Y;
    public javax.swing.JButton button_Z;
    public javax.swing.JButton button_Ñ;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    public javax.swing.JTextField txtPalabra;
    // End of variables declaration//GEN-END:variables
}
